#  server:
#  port: 因为会启动多个product-data-service 所以让用户自定义端口

spring:
  application:
     name: product-data-service
eureka:
   client:
      serviceUrl:
          defaultZone: http://localhost:8761/eureka/