spring:
  application.name: turbine
security.basic.enabled: false
turbine:
  aggregator:
    clusterConfig: default
  appConfig: product-view-service-feign
  clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
