spring:
  application:
    name: server-config
  cloud:
    config:
      lable: master
      server:
        git:
          uri: https://github.com/WindDogg/springcloudConfig/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/